# Generated by Django 2.2.7 on 2019-12-04 09:21

from django.db import migrations


class Migration(migrations.Migration):
    def create_default_group(apps, schema_editor):
        GroupModel = apps.get_model('auth', 'group')
        GroupModel(name='admin').save()
        GroupModel(name='production').save()
        GroupModel(name='user').save()
        GroupModel(name='viewer').save()
    
    dependencies = [
        ('auth', '__latest__'),
    ]
    operations = [
        migrations.RunPython(create_default_group),
    ]
